/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.intuit.review.feedback.mgmt.port.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class FeedbackNotification extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7351802152627713287L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FeedbackNotification\",\"namespace\":\"com.intuit.review.feedback.mgmt.port.avro\",\"fields\":[{\"name\":\"eventMetadata\",\"type\":{\"type\":\"record\",\"name\":\"EventMetadata\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"operation\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}},{\"name\":\"objectId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"objectType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"metadata\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Metadata\",\"fields\":[{\"name\":\"key\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FeedbackNotification> ENCODER =
      new BinaryMessageEncoder<FeedbackNotification>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FeedbackNotification> DECODER =
      new BinaryMessageDecoder<FeedbackNotification>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FeedbackNotification> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FeedbackNotification> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FeedbackNotification> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FeedbackNotification>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FeedbackNotification to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FeedbackNotification from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FeedbackNotification instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FeedbackNotification fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private EventMetadata eventMetadata;
   private String objectId;
   private String objectType;
   private java.util.List<Metadata> metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FeedbackNotification() {}

  /**
   * All-args constructor.
   * @param eventMetadata The new value for eventMetadata
   * @param objectId The new value for objectId
   * @param objectType The new value for objectType
   * @param metadata The new value for metadata
   */
  public FeedbackNotification(EventMetadata eventMetadata, String objectId, String objectType, java.util.List<Metadata> metadata) {
    this.eventMetadata = eventMetadata;
    this.objectId = objectId;
    this.objectType = objectType;
    this.metadata = metadata;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return eventMetadata;
    case 1: return objectId;
    case 2: return objectType;
    case 3: return metadata;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: eventMetadata = (EventMetadata)value$; break;
    case 1: objectId = value$ != null ? value$.toString() : null; break;
    case 2: objectType = value$ != null ? value$.toString() : null; break;
    case 3: metadata = (java.util.List<Metadata>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventMetadata' field.
   * @return The value of the 'eventMetadata' field.
   */
  public EventMetadata getEventMetadata() {
    return eventMetadata;
  }


  /**
   * Sets the value of the 'eventMetadata' field.
   * @param value the value to set.
   */
  public void setEventMetadata(EventMetadata value) {
    this.eventMetadata = value;
  }

  /**
   * Gets the value of the 'objectId' field.
   * @return The value of the 'objectId' field.
   */
  public String getObjectId() {
    return objectId;
  }


  /**
   * Sets the value of the 'objectId' field.
   * @param value the value to set.
   */
  public void setObjectId(String value) {
    this.objectId = value;
  }

  /**
   * Gets the value of the 'objectType' field.
   * @return The value of the 'objectType' field.
   */
  public String getObjectType() {
    return objectType;
  }


  /**
   * Sets the value of the 'objectType' field.
   * @param value the value to set.
   */
  public void setObjectType(String value) {
    this.objectType = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return The value of the 'metadata' field.
   */
  public java.util.List<Metadata> getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * @param value the value to set.
   */
  public void setMetadata(java.util.List<Metadata> value) {
    this.metadata = value;
  }

  /**
   * Creates a new FeedbackNotification RecordBuilder.
   * @return A new FeedbackNotification RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new FeedbackNotification RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FeedbackNotification RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new FeedbackNotification RecordBuilder by copying an existing FeedbackNotification instance.
   * @param other The existing instance to copy.
   * @return A new FeedbackNotification RecordBuilder
   */
  public static Builder newBuilder(FeedbackNotification other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for FeedbackNotification instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FeedbackNotification>
    implements org.apache.avro.data.RecordBuilder<FeedbackNotification> {

    private EventMetadata eventMetadata;
    private EventMetadata.Builder eventMetadataBuilder;
    private String objectId;
    private String objectType;
    private java.util.List<Metadata> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventMetadata)) {
        this.eventMetadata = data().deepCopy(fields()[0].schema(), other.eventMetadata);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasEventMetadataBuilder()) {
        this.eventMetadataBuilder = EventMetadata.newBuilder(other.getEventMetadataBuilder());
      }
      if (isValidValue(fields()[1], other.objectId)) {
        this.objectId = data().deepCopy(fields()[1].schema(), other.objectId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.objectType)) {
        this.objectType = data().deepCopy(fields()[2].schema(), other.objectType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.metadata)) {
        this.metadata = data().deepCopy(fields()[3].schema(), other.metadata);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing FeedbackNotification instance
     * @param other The existing instance to copy.
     */
    private Builder(FeedbackNotification other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventMetadata)) {
        this.eventMetadata = data().deepCopy(fields()[0].schema(), other.eventMetadata);
        fieldSetFlags()[0] = true;
      }
      this.eventMetadataBuilder = null;
      if (isValidValue(fields()[1], other.objectId)) {
        this.objectId = data().deepCopy(fields()[1].schema(), other.objectId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.objectType)) {
        this.objectType = data().deepCopy(fields()[2].schema(), other.objectType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.metadata)) {
        this.metadata = data().deepCopy(fields()[3].schema(), other.metadata);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'eventMetadata' field.
      * @return The value.
      */
    public EventMetadata getEventMetadata() {
      return eventMetadata;
    }


    /**
      * Sets the value of the 'eventMetadata' field.
      * @param value The value of 'eventMetadata'.
      * @return This builder.
      */
    public Builder setEventMetadata(EventMetadata value) {
      validate(fields()[0], value);
      this.eventMetadataBuilder = null;
      this.eventMetadata = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventMetadata' field has been set.
      * @return True if the 'eventMetadata' field has been set, false otherwise.
      */
    public boolean hasEventMetadata() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'eventMetadata' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public EventMetadata.Builder getEventMetadataBuilder() {
      if (eventMetadataBuilder == null) {
        if (hasEventMetadata()) {
          setEventMetadataBuilder(EventMetadata.newBuilder(eventMetadata));
        } else {
          setEventMetadataBuilder(EventMetadata.newBuilder());
        }
      }
      return eventMetadataBuilder;
    }

    /**
     * Sets the Builder instance for the 'eventMetadata' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public Builder setEventMetadataBuilder(EventMetadata.Builder value) {
      clearEventMetadata();
      eventMetadataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'eventMetadata' field has an active Builder instance
     * @return True if the 'eventMetadata' field has an active Builder instance
     */
    public boolean hasEventMetadataBuilder() {
      return eventMetadataBuilder != null;
    }

    /**
      * Clears the value of the 'eventMetadata' field.
      * @return This builder.
      */
    public Builder clearEventMetadata() {
      eventMetadata = null;
      eventMetadataBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'objectId' field.
      * @return The value.
      */
    public String getObjectId() {
      return objectId;
    }


    /**
      * Sets the value of the 'objectId' field.
      * @param value The value of 'objectId'.
      * @return This builder.
      */
    public Builder setObjectId(String value) {
      validate(fields()[1], value);
      this.objectId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'objectId' field has been set.
      * @return True if the 'objectId' field has been set, false otherwise.
      */
    public boolean hasObjectId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'objectId' field.
      * @return This builder.
      */
    public Builder clearObjectId() {
      objectId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'objectType' field.
      * @return The value.
      */
    public String getObjectType() {
      return objectType;
    }


    /**
      * Sets the value of the 'objectType' field.
      * @param value The value of 'objectType'.
      * @return This builder.
      */
    public Builder setObjectType(String value) {
      validate(fields()[2], value);
      this.objectType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'objectType' field has been set.
      * @return True if the 'objectType' field has been set, false otherwise.
      */
    public boolean hasObjectType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'objectType' field.
      * @return This builder.
      */
    public Builder clearObjectType() {
      objectType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * @return The value.
      */
    public java.util.List<Metadata> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public Builder setMetadata(java.util.List<Metadata> value) {
      validate(fields()[3], value);
      this.metadata = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'metadata' field.
      * @return This builder.
      */
    public Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FeedbackNotification build() {
      try {
        FeedbackNotification record = new FeedbackNotification();
        if (eventMetadataBuilder != null) {
          try {
            record.eventMetadata = this.eventMetadataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("eventMetadata"));
            throw e;
          }
        } else {
          record.eventMetadata = fieldSetFlags()[0] ? this.eventMetadata : (EventMetadata) defaultValue(fields()[0]);
        }
        record.objectId = fieldSetFlags()[1] ? this.objectId : (String) defaultValue(fields()[1]);
        record.objectType = fieldSetFlags()[2] ? this.objectType : (String) defaultValue(fields()[2]);
        record.metadata = fieldSetFlags()[3] ? this.metadata : (java.util.List<Metadata>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FeedbackNotification>
    WRITER$ = (org.apache.avro.io.DatumWriter<FeedbackNotification>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FeedbackNotification>
    READER$ = (org.apache.avro.io.DatumReader<FeedbackNotification>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.eventMetadata.customEncode(out);

    out.writeString(this.objectId);

    out.writeString(this.objectType);

    if (this.metadata == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.metadata.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (Metadata e0: this.metadata) {
        actualSize0++;
        out.startItem();
        e0.customEncode(out);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.eventMetadata == null) {
        this.eventMetadata = new EventMetadata();
      }
      this.eventMetadata.customDecode(in);

      this.objectId = in.readString();

      this.objectType = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.metadata = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<Metadata> a0 = this.metadata;
        if (a0 == null) {
          a0 = new SpecificData.Array<Metadata>((int)size0, SCHEMA$.getField("metadata").schema().getTypes().get(1));
          this.metadata = a0;
        } else a0.clear();
        SpecificData.Array<Metadata> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<Metadata>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            Metadata e0 = (ga0 != null ? ga0.peek() : null);
            if (e0 == null) {
              e0 = new Metadata();
            }
            e0.customDecode(in);
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.eventMetadata == null) {
            this.eventMetadata = new EventMetadata();
          }
          this.eventMetadata.customDecode(in);
          break;

        case 1:
          this.objectId = in.readString();
          break;

        case 2:
          this.objectType = in.readString();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.metadata = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<Metadata> a0 = this.metadata;
            if (a0 == null) {
              a0 = new SpecificData.Array<Metadata>((int)size0, SCHEMA$.getField("metadata").schema().getTypes().get(1));
              this.metadata = a0;
            } else a0.clear();
            SpecificData.Array<Metadata> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<Metadata>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                Metadata e0 = (ga0 != null ? ga0.peek() : null);
                if (e0 == null) {
                  e0 = new Metadata();
                }
                e0.customDecode(in);
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










